Volume
HunkiKim/oss-edu pull request #19
Opened 2023-05-23 14:35 UTC by HunkiKim

- Volume
  - Docker에서의 볼륨
  - k8s의 볼륨
  - 사용 가능한 볼륨 유형
- 볼륨을 사용한 컨테이너간 데이터 공유
  - emptyDir
  - hotsPath
  - gitRepo
  - PV
  - PVC
  - 동적 프로비저닝

2023-05-24 07:16 UTC, HunkiKim commented
볼륨쪽 아래 내용 수정했습니다!
- 볼륨이 나온 배경
- hostPath 배경
    - 접근하면 안된다 X -> 못한다
- PV yaml파일 storage 수정
- PV lifecycle
- pv, pvc, pod 꺼지는걸 방지하는걸 어떻게 유지하지는지
    - finalizers
    - deletetionTimestamp

2023-05-26 02:42 UTC, mantech-mjkim requested changes

2023-05-26 02:42 UTC, mantech-mjkim commented on kubernetes/volume.md
> +- 위의 pod들의 경우엔 configmap이 주된 볼륨을 사용한다.
`hostPath` 볼륨 정보나 테스트로 적절하지 않습니다.
`hostPath` 볼륨 테스트를 작성해주세요.

2023-05-26 02:42 UTC, mantech-mjkim commented on kubernetes/volume.md
> +## PVC 생성을 통한 PV 요청
`PV - PVC 바인딩`으로 제목을 변경해주세요.

2023-05-26 02:42 UTC, mantech-mjkim commented on kubernetes/volume.md
> +## 파드에서 PVC 사용하기
PVC는 볼륨을 구성하기 위한 리소스 중 하나로 파드에서 PVC를 선언하지만 PVC를 사용한다기보다 실제로는 볼륨을 사용하기 위해 PVC를 선언하는 것으로 `파드에서 볼륨 사용하기`가 좀더 적절할 것 같습니다.

2023-05-26 02:42 UTC, mantech-mjkim requested changes
gitRepo는 deprecated되어 관련 내용은 제거해주세요.
참조: https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo

2023-08-16 23:51 UTC, merged